version=1.0.0
author=Nicholas T. <ntoutges@gmail.com>
maintainer=Nicholas T. <ntoutges@gmail.com>
sentence=A simple, fast, lightweight cooperative scheduler built in C.
paragraph=All memory is owned by the user and managed by the scheduler. This scheduler requires no interrupts, has minimal memory/CPU usage, and is fully extensible.
category=Other
url=https://github.com/ntoutges/csch